version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
 
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64 
    image: mysql:8
    ports:
      - 13306:3306
    volumes:
      - db-data:/var/lib/mysql
      # - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
 db-data:
